dataset: "FOOD101"
root: "../datasets"
backbone: "ViT-B/16"
resolution: 256
stride: 16

output_dir: null
resume: null
checkpoint_freq: 0
print_freq: 10

seed: null
deterministic: False
gpu: null
num_workers: 8
prec: "fp16"

num_epochs: 30
lr: 0.03
weight_decay: 5e-4
momentum: 0.9

DATA:
  NAME: "FOOD101"
  DATAPATH: "../datasets"  #TODO: need to specify here
  NUMBER_CLASSES: 101
  NUM_L: 5
  NUM_U: 400
  IMB_L: 1.0
  IMB_U: 1.0
  MU_U: 1
  BATCH_SIZE: 32

finetune: False
bias_tuning: False
vpt_shallow: False
vpt_deep: False
vpt_last: False
lam_tokens: 1.0

vpt_len: 50
adapter: False
adapter_dim: 8
lora: False
lora_dim: 8
ssf: False

th: 0.7
mode: 0
alpha: 8.0
w_con: 3.0
smoothing: 0.5
