dataset: "semi_ImageNet"
root: "Path to ImageNet"
backbone: "ViT-B/16"
resolution: 224
stride: 16

output_dir: null
resume: null
checkpoint_freq: 0
print_freq: 10

seed: null
deterministic: False
gpu: null
num_workers: 8
prec: "fp16"

num_epochs: 30
batch_size: 32
lr: 0.03
weight_decay: 5e-4
momentum: 0.9

tau: 1.0

DATA:
  NAME: "semi_ImageNet"
  DATAPATH: "Path to ImageNet"
  NUMBER_CLASSES: 1000
  BATCH_SIZE: 16
  LABEL_RATIO: 0.01

bias_tuning: False
vpt_shallow: False
vpt_deep: False
vpt_len: 50
adapter: False
adapter_dim: 8
lora: False
lora_dim: 8
ssf: False

th: 0.7

alpha: 8.0
w_con: 3.0
smoothing: 0.5
total_steps: 500
